version: '3.7'

networks:
  mimasflix-network:
    external: true

services:
  mimasflix-customer:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    entrypoint: ./entrypoint.sh
    container_name: mimasflix-customer
    image: mimasflix-customer:latest
    environment:
      APP_PORT: ${APP_PORT}
      APP_NAME: ${APP_NAME}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      AUTHOR_NAME: ${AUTHOR_NAME}
      AUTHOR_EMAIL: ${AUTHOR_EMAIL}
      BASE_PATH: ${BASE_PATH}
      DOCS_PATH: ${DOCS_PATH}
      FRAMEWORK: ${FRAMEWORK}
      SONAR_LOGIN: ${SONAR_LOGIN}
      SONAR_PASSWORD: ${SONAR_PASSWORD}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      SONAR_SERVER_URL: ${SONAR_SERVER_URL}
      SONAR_PORT: ${SONAR_PORT}
      LOGS_FOLDER: ${LOGS_FOLDER}
      NODE_ENV: ${NODE_ENV}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - mimasflix-network
    volumes:
      - .:/home/node/app/mimasflix-customer

  postgres:
    container_name: postgres
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_DATABASE: ${DATABASE_DATABASE}
      POSTGRESQL_TIMEZONE: America/SAO_PAULO
    ports:
      - "${DATABASE_PORT}:5432"
    restart: on-failure
    networks:
      - mimasflix-network
    volumes:
      - .:/home/postgresql/data

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    networks:
      - mimasflix-network
    ports:
      - '${SONAR_PORT}:${SONAR_PORT}'
      - '9092:9092'
