# Quando trocar essa versão do node, trocar também no arquivo .nvmrc
FROM node:16.14.0-alpine

RUN apk add --no-cache bash
# RUN npm install -g yarn
RUN npm config set cache /home/node/app/mimasflix-customer/.npm-cache --global

RUN mkdir -p /home/node/app/mimasflix-customer

USER node

WORKDIR /home/node/app/mimasflix-customer
